# Generated by Django 2.2 on 2019-07-20 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('mobile', models.CharField(max_length=15, verbose_name='phone_number')),
                ('course_name', models.CharField(max_length=50, verbose_name='course_name')),
            ],
            options={
                'verbose_name': 'User_inquire',
                'verbose_name_plural': 'User_inquire',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('message', models.CharField(max_length=200, verbose_name='user_message')),
                ('has_read', models.BooleanField(default=False, verbose_name='read_or_unread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'user_msg',
                'verbose_name_plural': 'user_msg',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('fav_id', models.IntegerField(verbose_name='digital_id')),
                ('fav_type', models.IntegerField(choices=[(1, 'course'), (2, 'course_oganization'), (3, 'teacher')], default=1, verbose_name='subscribe_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'user_subscribe',
                'verbose_name_plural': 'user_subscribe',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'user_course',
                'verbose_name_plural': 'user_course',
            },
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('comments', models.CharField(max_length=200, verbose_name='comments')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'course_comments',
                'verbose_name_plural': 'course_comments',
            },
        ),
    ]
