# Generated by Django 2.2 on 2019-07-26 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
    ]
