# Generated by Django 2.2 on 2019-07-20 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('name', models.CharField(max_length=50, verbose_name='course_name')),
                ('desc', models.CharField(max_length=300, verbose_name='course_description')),
                ('learn_time', models.IntegerField(default=0, verbose_name='total_learning_tiem (min)')),
                ('degree', models.CharField(choices=[('bg', 'beginner'), ('im', 'intermediate'), ('ep', 'expert')], max_length=2, verbose_name='difficult')),
                ('student', models.IntegerField(default=0, verbose_name='learning_student_current')),
                ('fav_number', models.IntegerField(default=0, verbose_name='subscribe_number')),
                ('click_number', models.IntegerField(default=0, verbose_name='clicked_number')),
                ('category', models.CharField(default='backend_develop', max_length=20, verbose_name='class_type')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='class_tag')),
                ('class_info', models.CharField(default='', max_length=300, verbose_name='class_general_intro')),
                ('teacher_reg', models.CharField(default='', max_length=300, verbose_name='recommendation')),
                ('detail', models.TextField(verbose_name='class_detail')),
                ('image', models.ImageField(upload_to='course/%Y%m', verbose_name='cover_image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Course_Info',
                'verbose_name_plural': 'Course_Info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('name', models.CharField(max_length=100, verbose_name='chapter_name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='total_learning_time(mins)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'Lesson_Chapter',
                'verbose_name_plural': 'Lesson_Chapter',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('name', models.CharField(max_length=100, verbose_name='video_name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='total_learning_time(mins)')),
                ('url', models.URLField(verbose_name='video_url_address')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'uploaded_video',
                'verbose_name_plural': 'uploaded_video',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='add_current_time')),
                ('name', models.CharField(max_length=100, verbose_name='resource_download')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y%m', verbose_name='download_address')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course_resource')),
            ],
            options={
                'verbose_name': 'Course_Resource',
                'verbose_name_plural': 'Course_Resource',
            },
        ),
    ]
