# Generated by Django 2.2 on 2019-07-26 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='city',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('tc', 'training_camp'), ('pe', 'personal'), ('hr', 'high_rank_school')], default='training_camp', max_length=10, verbose_name='organization_type'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='national_popular', max_length=20, verbose_name='tag_organization'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
    ]
